<!DOCTYPE html>
<html lang="zh-cn">
<head>
<meta charset="utf-8"/>
<style type="text/css">
    body{
        width: 1300px;
        margin-left: auto;
        margin-right: auto;
        background-image: url(https://img.tukuppt.com/ad_preview/00/19/83/5c9a07f3b6f08.jpg!/fw/980);
    }
    h1.title{
        font-weight: bold;
        font-size: 60px;
        color: rgb(255,255,255);
    }
    h2.title{
        font-weight: bold;
        font-size: 24px;
        color: rgb(218, 165, 32);
    }
    h3.title{
        font-weight: bold;
        font-size: 18px;
        color: rgb(218, 165, 32);
    }
    .article{
        color: darkgoldenrod;
    }
    .link{
        color: gold;
    }
    #heading{
        width: 1300px;
        border-width: 1px;
        border-style: solid;
        border-color: gold;
        padding-left: 20px;
        padding-right: 20px;
        padding-top: 20px;
        padding-bottom: 20px;
        margin: 5px;
        background-color: rgba(218,165,32,1);
    }
    #menu{
        display: table;
        width: 1300px;
    }
    #m1,#m2,#m3{
        display: table-cell;
    }
    #m1{
        border-width: 1px;
        border-color: gold;
        border-style: solid;
        width: 433px;
        padding-left: 20px;
        padding-right: 20px;
        padding-top: 20px;
        padding-bottom: 20px;
        margin: 5px;
        background-color: rgba(255,235,205,0.5);
    }
    #m2{
        border-width: 1px;
        border-color: gold;
        border-style: solid;
        width: 433px;
        padding-left: 20px;
        padding-right: 20px;
        padding-top: 20px;
        padding-bottom: 20px;
        margin: 5px;
        background-color: rgba(255,235,205,0.5);
    }
    #m3{
        border-width: 1px;
        border-color: gold;
        border-style: solid;
        width: 433px;
        padding-left: 20px;
        padding-right: 20px;
        padding-top: 20px;
        padding-bottom: 20px;
        margin: 5px;
        background-color: rgba(255,235,205,0.5);
    }
    #hometown{
        border-width: 1px;
        border-color: gold;
        border-style: solid;
        width: 1300px;
        padding-left: 20px;
        padding-right: 20px;
        padding-top: 20px;
        padding-bottom: 20px;
        margin: 5px;
        background-color: rgba(255,235,205,0.5);
    }
    #intro{
        border-width: 1px;
        border-color: gold;
        border-style: solid;
        width: 1300px;
        padding-left: 20px;
        padding-right: 20px;
        padding-top: 20px;
        padding-bottom: 20px;
        margin: 5px;
        background-color: rgba(255,235,205,0.5);
    }
    #hobby{
        display: table;
        width: 1300px;
    }
    #hobby1,#hobby2,#hobby3{
        display: table-cell;
    }
    #hobby1{
        border-width: 1px;
        border-color: gold;
        border-style: solid;
        width: 500px;
        padding-left: 20px;
        padding-right: 20px;
        padding-top: 20px;
        padding-bottom: 20px;
        margin: 5px;
        background-color: rgba(255,235,205,0.5);
    }
    #hobby2{
        border-width: 1px;
        border-color: gold;
        border-style: solid;
        width: 400px;
        padding-left: 20px;
        padding-right: 20px;
        padding-top: 20px;
        padding-bottom: 20px;
        margin: 5px;
        background-color: rgba(255,235,205,0.5);
    }
    #hobby3{
        border-width: 1px;
        border-color: gold;
        border-style: solid;
        width: 400px;
        padding-left: 20px;
        padding-right: 20px;
        padding-top: 20px;
        padding-bottom: 20px;
        margin: 5px;
        background-color: rgba(255,235,205,0.5);
    }
    #ending{
        border-width: 1px;
        border-color: gold;
        border-style: solid;
        width: 1300px;
        padding-left: 20px;
        padding-right: 20px;
        padding-top: 20px;
        padding-bottom: 20px;
        margin: 5px;
        background-color: rgba(255,235,205,0.5);
    }
    *{box-sizing: border-box;}
    .row1 .col{
        float: left;
        width: 200px;
    }
    img.headimg{
        float: left;
    }
    div.heading-end{
        clear: both;
    }
    img.homeimg{
        float: left;
    }
    div.hometown-end{
        clear: both;
    }
    img.hobbyimg1{
        float: left;
    }
    div.hobby2-end{
        clear: both;
    }
    img.hobbyimg2{
        float: left;
    }
    div.hobby3-end{
        clear: both;
    }
</style>
<title>是冬同学的简陋主页</title>
</head>
<body>
 <div id="heading">
    <h1 class="title">你好！我是Summer！</h1>
 </div>
 <div id="menu">
    <div id="m1">
       <p class="article">Intro</p>
    </div>
    <div id="m2">
       <p class="article">Hometown</p>
    </div>
    <div id="m3">
        <p class="article">Hobby</p>
    </div>        
 </div>
 <div id="intro">
    <h2 class="title">非常简略的介绍</h2>
    <p class="article">欢迎点进这个超简陋主页！我是一名普通的PKU药学大一新生！来自广西桂林，是爱打游戏爱摸鱼的懒狗（。）……如果你感兴趣的话，还请继续往下看（啊？）！</p>
 </div>
 <div id="hometown">
    <h2 class="title">关于我的家乡</h2>
    <p class="article">相信很多人都听说过“桂林山水甲天下”，是的，我们桂林有山有水风景好，不仅有象鼻山、独秀峰等知名景点，市区内也处处可见奇形怪状（？）的小山；两江四湖（漓江、桃花江、桂湖、榕湖、杉湖、木龙湖）无论是沿岸行走还是乘船漂游都是美景！而桂林米粉也是美味经典的桂林早餐（你想作午晚餐吃也不是不可以……）！欢迎大家来桂林玩哦！可以抓我做免费导游（bushi）。</p>
    <img class="homeimg" src="https://tse1-mm.cn.bing.net/th/id/R-C.1fba92ff3cb06eafdadfa1364ef23ca0?rik=5Cn8fwfeIVMqcA&riu=http%3a%2f%2fwww.glljsh.com%2fkw-content%2fuploads%2f2018%2f08%2f03%2f5b64002081fa7.png&ehk=J49W%2fP545Z%2fkBu4JADhvjwmPcg3CV2ddth7QGWETNrs%3d&risl=&pid=ImgRaw&r=0">
    <a class="link" href="http://www.mafengwo.cn/travel-scenic-spot/mafengwo/10095.html">如果你还想继续深入了解桂林，可以康康这里！</a>
    <div class="hometown-end"></div>
 </div>
<div id="hobby">
 <div id="hobby1">
    <h2 class="title">一点点爱好</h2>
    <h3 class="title">你看这个人打游戏就是菜啦.jpg</h3>
    <p class="article">人菜瘾还大的游戏宅（。），由于社交力弱弱弱游戏力菜菜菜所以是单机游戏爱好者，steam库、ps4、switch里游戏长期积灰（买了就是玩了.jpg），最近在玩的游戏包括但不限于：</p>
    <!--<div class="row1">
        <div class="col"><img src="https://tse1-mm.cn.bing.net/th/id/OIP-C.kHQzh2FDofoi72f25LP8rQHaJ3?w=148&h=198&c=7&r=0&o=5&dpr=1.5&pid=1.7"></div>
        <div class="col"><img src="https://tse4-mm.cn.bing.net/th/id/OIP-C.z_i9TQVoJLzT8hxEdBHRrwHaL_?w=117&h=190&c=7&r=0&o=5&dpr=1.5&pid=1.7"></div>
        <div class="col"><img src="https://tse3-mm.cn.bing.net/th/id/OIP-C.nR3MGpLVxdNN4lRg6f0LlgHaKg?w=115&h=180&c=7&r=0&o=5&dpr=1.5&pid=1.7"></div>
        <div class="col"><img src="https://tse1-mm.cn.bing.net/th/id/OIP-C.o-RBJ5C6Afoy2rVAAxUARgHaJQ?w=200&h=250&c=7&r=0&o=5&dpr=1.5&pid=1.7"></div>
        <div class="col"><img src="https://tse4-mm.cn.bing.net/th/id/OIP-C.uKhyhKhd__tjOsV0_2VyvgAAAA?w=115&h=180&c=7&r=0&o=5&dpr=1.5&pid=1.7"></div>
    </div>-->
    <ul class="article">
        <li>刺客信条：起源（准备玩玩其他同系列游戏）</li>
        <li>塞尔达传说：旷野之息</li>
        <li>muse dash(弱弱音游人)</li>
        <li>……</li>
    </ul>
    <p class="article">总而言之，有好玩的游戏欢迎安利……</p>
 </div>
 <div id="hobby2">
    <h3 class="title">教练！我想打篮球！</h3>
    <p class="article">虽然这个人是阿宅但是是爱运动的阿宅（。），所有会的运动都可以归类为“人菜瘾大”。包括但不限于：篮球、游泳、排球（只会打气排球的屑），跑步，etc。最近在努力学习篮球中，欢迎球友来吊打（划掉）与我交流（x）。</p>
    <img class="hobbyimg1"src="https://tse3-mm.cn.bing.net/th/id/OIP-C.VEmrggR1AeTdMKAisBIaygAAAA?w=136&h=154&c=7&r=0&o=5&dpr=1.5&pid=1.7">
    <div class="hobby2-end"></div>
 </div>
 <div id="hobby3">
    <h3 class="title">音乐、书籍之类的</h3>
    <p class="article">喜欢听好听的音乐，不喜欢听不好听的音乐；喜欢看好看的书，不喜欢看不好看的书……（听君一席话，如听一席话.jpg）总之就是啥都听，也啥都看。最近是虚假的摇滚爱好者，比较喜欢Queen的歌！</p>
    <!--<img class="hobbyimg2" src="https://tse1-mm.cn.bing.net/th/id/R-C.43c6bca60ffad45fe7e1533ac9ea9452?rik=KP3ckaGVSeYeEQ&riu=http%3a%2f%2fphotocdn.sohu.com%2f20080805%2fImg258613387.jpg&ehk=apKlCa9LihiYnvM%2bultRLS1H1QgI6kfIX2QnnaYgDKo%3d&risl=&pid=ImgRaw&r=0">
    <div class="hobby3-end"></div>-->
 </div>
</div>
 <div id="ending">
    <img class="headimg" src="https://i0.hdslb.com/bfs/album/8734348d086fb18700ddd661e4ed435511b22522.jpg@518w.webp">
    <p class="article">写到最后不想写嘞（？），总之欢迎大噶来找我玩，嘻嘻🤭</p>
    <p class="link">wx:15676368587</p>
    <div class="heading-end"></div>
 </div>
</body>
</html>
